import * as SessionAPIUtil from "../utils/user_api_util";

export const RECEIVE_CURRENT_PROFILE_ERRORS = "RECEIVE_CURRENT_PROFILE_ERRORS";
export const RECEIVE_CURRENT_USER_PROFILE = "RECEIVE_CURRENT_USER_PROFILE";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
