# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

User.destroy_all
User.create(email:"David@gmail.com", password: "password", first_name: "David", last_name: "Wong")
User.create(email:"Vader@gmail.com", password: "password", first_name: "Darth Vader", last_name: "Skywalker")
User.create(email:"Kenobi@gmail.com", password: "password", first_name: "Ben", last_name: "Kenobi")
User.create(email: "Tigh@gmail.com", password: "password", first_name: "Saul", last_name: "Tigh")
User.create(email: 'Sanchez@gmail.com', password: "password", first_name: "Rick", last_name: "Sanchez")
User.create(email: 'Smith@gmail.com', password: 'password', first_name: 'Morty', last_name: 'Smith')
User.create(email: 'Potter@gmail.com', password: 'password', first_name: 'Harry', last_name: 'Potter')
User.create(email: 'Bond@gmail.com', password: 'password', first_name: 'James', last_name: 'Bond')
User.create(email: 'Geller@gmail.com', password: 'password', first_name: 'Ross', last_name: 'Geller')
User.create(email: 'Strife@gmail.com', password: 'password', first_name: 'Cloud', last_name: 'Strife')
User.create(email: 'Janeway@gmail.com', password: 'password', first_name: 'Kathryn', last_name: 'Janeway')
User.create(email: 'Torres@gmail.com', password: 'password', first_name: 'B\'Elanna', last_name: 'Torres')
User.create(email: 'Birdman@gmail.com', password: 'password', first_name: 'Bird', last_name: 'Man')
User.create(email: 'Nerys@gmail.com', password: 'password', first_name: 'Kira', last_name: 'Nerys')
User.create(email: 'Odo@gmail.com', password: 'password', first_name: 'None', last_name: 'Odo')
User.create(email: 'Wayne@gmail.com', password: 'password', first_name: 'Bruce', last_name: 'Wayne')
User.create(email: 'Wilson@gmail.com', password: 'password', first_name: 'Wade', last_name: 'Wilson')
User.create(email: 'Garak@gmail.com', password: 'password', first_name: 'Elim', last_name: 'Garak')
User.create(email: 'Snow@gmail.com', password: 'password', first_name: 'Jon', last_name: 'Snow')
User.create(email: 'Solo@gmail.com', password: 'password', first_name: 'Han', last_name: 'Solo')
User.create(email: 'Solid@gmail.com', password: 'password', first_name: 'Solid', last_name: 'Snake')
User.create(email: 'Liquid@gmail.com', password: 'password', first_name: 'Liquid', last_name: 'Snake')
User.create(email: 'Campbell@gmail.com', password: 'password', first_name: 'Roy', last_name: 'Campbell')
User.create(email: 'Archer@gmail.com', password: 'password', first_name: 'Sterling', last_name: 'Archer')
User.create(email: 'Saitama@gmail.com', password: 'password', first_name: 'Caped Baldy', last_name: 'Saitama')
User.create(email: 'Lemon@gmail.com', password: 'password', first_name: 'Elizabeth', last_name: 'Lemon')
User.create(email: 'Donaughy@gmail.com', password: 'password', first_name: 'Jack', last_name: 'Donaughy')
User.create(email: 'Picard@gmail.com', password: 'password', first_name: 'Jean Luc', last_name: 'Picard')
User.create(email: 'Rosie@gmail.com', password: 'password', first_name: 'Rosie', last_name: 'Jetson')
User.create(email: 'Scooby@gmail.com', password: 'password', first_name: 'Scooby', last_name: 'Doo')
User.create(email: 'Finn@gmail.com', password: 'password', first_name: 'Finn', last_name: 'The Human')
User.create(email: 'Jake@gmail.com', password: 'password', first_name: 'Jake', last_name: 'The Dog')
